filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/www/log/order-monitor.log

output.logstash:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # The Logstash hosts
  hosts: ["localhost:5001"]
